import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import HeroImage from '../images/hero-img-trade-tracker.png';
import AppPreviewImg from '../images/app-preview.png';
import IconChart from '../images/svgs/icon-chart-up.svg';
import IconPie from '../images/svgs/icon-pie-chart.svg';
import IconClipboard from '../images/svgs/icon-clipboard.svg';
import IconFlag from '../images/svgs/icon-flag.svg';
import PhoneView from '../images/phone-app-view.jpg'



import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Trade Tracker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-[#FFFFFF] to-[var(--gradient-color)]">
        <div className="container flex flex-col items-center justify-center py-12 ">
          <h1 className="text-4xl font-extrabold tracking-tight text-center text-slate-950 lg:text-[5rem]">
            Track & improve your trades
          </h1>
          <p className="text-center">Gain consistency through data. View insights and performance of your trades over time.</p>
          <Link
              className="flex max-w-xl flex-col gap-4 rounded-sm bg-main-teal py-4 px-12 text-slate-950 hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
            <span className="font-bold text-slate-50 ">Explore Now →</span>
          </Link>
          <Image 
            src={HeroImage}
            alt='Trade Tracker Hero Image'
          />

          <div className="grid grid-cols-1 gap-4 py-28 sm:grid-cols-2 md:gap-8 bg-main-pattern bg-cover px-4 text-slate-50">
              <h2 className="text-2xl font-bold">Track. Analyze. Progress.</h2>
              <p>Built-in tools to help you maximize your winning trades and decrease your losing ones. Build up a proven history of wins to help you break out to the next level.</p>
          </div>

          <div className="grid grid-cols-1 gap-4 py-28 sm:grid-cols-2 md:gap-8 bg-[var(--dark-1)] bg-cover px-4 text-slate-50">
              <h2 className="text-2xl font-bold">Redefining the stock journal.</h2>
              <p>Practice makes perfect, and Trade Tracker improves your steady progress with intuitive features.</p>
              <Link
                  className="flex max-w-xl flex-col gap-4 text-center rounded-sm bg-main-teal py-4 px-12 text-slate-950 hover:bg-white/20"
                  href="https://create.t3.gg/en/introduction"
                  target="_blank"
                >
                <span className="font-bold text-slate-50 ">See Metrics →</span>
              </Link>
          </div>

          <div className="py-28 px-4">
            <h2 className="text-4xl font-bold text-center">Unlocking new paradigms</h2>
            <Image 
              src={AppPreviewImg}
              alt='Trade Tracker App Preview'
            />

          </div>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8 px-8 py-16 text-slate-50 bg-pattern-2 bg-cover">
            <h3 className="text-lg">Why Trade Tracker?</h3>
            <h2 className="text-2xl font-bold text-slate-950">Habit and performance</h2>

            <div>
              <IconChart className='text-6xl'/>
              <h4 className="font-bold">Customizable charts</h4>
              <p>Create charts based on the metrics you want to track.</p>
            </div>

            <div>
              <IconPie className='text-6xl'/>
              <h4 className="font-bold">Analyze portfolios</h4>
              <p>Personal, retirement, crypto, options, you name it. </p>
            </div>

            <div>
              <IconClipboard className='text-6xl'/>
              <h4 className="font-bold">Evaluate trades</h4>
              <p>Get a new perspective on past trades and how to improve.</p>
            </div>

            <div>
              <IconFlag className='text-6xl'/>
              <h4 className="font-bold">Personalized Notes</h4>
              <p>Create shortcuts and reminders to get you performing to your best.</p>
            </div>
          </div>

          <div className="py-16 px-8 bg-white">
            <h3 className="text-lg text-mail-teal">Level up</h3>
            <h2 className="text-2xl font-bold text-slate-950">Watch your progress</h2>
            <p>Gain consistency through data. View insights and performance of your trades over time. Unlock your highest level of performance now.</p>
            <Link
                  className="flex max-w-xl flex-col gap-4 text-center rounded-sm bg-main-teal py-4 px-12 text-slate-950 hover:bg-white/20"
                  href="https://create.t3.gg/en/introduction"
                  target="_blank"
                >
                <span className="font-bold text-slate-50 ">Start free trail →</span>
              </Link>

              <Image 
                src={PhoneView}
                alt='Trade Tracker Phone App View'
              />
          </div>
          
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-slate-950 hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-slate-950 hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-slate-950">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-slate-950">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-slate-950 no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
